import React from "react";
import NameGenerator from "./NameGenerator.js"
import "./style.css";

export default function App() {
  return (
    <div>
      <h1>Custom Name Generator</h1>
      <p>A React-based custom name generator, which takes user input to randomly generate a wide variety of names.</p>
      <p>A name is generated by randomly selecting a line from each text box, and then putting them together. Some generic names and words have been added to the three boxes to demonstrate this.</p>
      <p>Edit or add your own names, words, name fragments, etc to the text boxes and hit the "Generate Name" button to create a randomly generated name!</p>
      <NameGenerator/>
    </div>
  );
}
